export const ActionTypes = {
  SET_TASK: "SET_TASK",
  FETCH_TASKS: "FETCH_TASKS",
  SELECTED_TASK: "SELECTED_TASK",
  REMOVE_SELECTED_TASK: "REMOVE_SELECTED_TASK",
  SET_PROJECT_LISTS: "SET_PROJECT_LISTS",
};
