export default {
  profile: "Profile",
  logout: "Logout",
  change: "Change",
  filters: "Filters",
  project: "Project",
  task: "Task",
  projectName: "Project Name",
  status: "Status",
  active: "active",
  inactive: "inactive",
  applyFilter: "Apply filters",
  clearFilter: "Clear filters",
  SearchProjectName: "Search Project Name",
  SearchSome: "Search something...",
  addTask: "add Task",
  edit: "Edit",
  delete: "Delete",
  SINo: "SI.No",
  taskName: "Task Name",
  progress: "Progress",
  completionDate: "Completion Date",
  projectAssignee: "Project Assignee",
  action: "Action",
  changeLanguage: "Change your langauge",
  startDate: "Start Date",
  enddate: "End Date",
  developer: "Developer",
  selectDeveloper: "Select Developer",
  sortBy: "Sort by:",
  all: "all",
  projectDescription: "Project Description",
  projectStatus: "Project Status",
  addProject: "Add Project",
};
