export default {
  changeLanguage: "अपनी भाषा बदलें",
  profile: "रूपरेखा",
  change: "परिवर्तन",
  logout: "लॉग आउट",
  filters: "छानना",
  projectName: "परियोजना का नाम",
  project: "परियोजना",
  task: "टास्क",
  status: "स्थिति",
  active: "सक्रिय",
  inactive: "निष्क्रिय",
  applyFilter: "फ़िल्टर लागू करें",
  clearFilter: "फ़िल्टर साफ़ करें",
  SearchProjectName: "खोज परियोजना का नाम",
  SearchSome: "कुछ खोजें...",
  addTask: "कार्य जोड़ें",
  edit: "संपादित करें",
  delete: "हटाएं",
  SINo: "क्रमिक संख्या",
  taskName: "कार्य का नाम",
  progress: "प्रगति",
  completionDate: "समापन तारीख",
  projectAssignee: "प्रोजेक्ट असाइनी",
  action: "कार्य",
  startDate: "आरंभ करने की तिथि",
  enddate: "समाप्ति तिथि",
  developer: "डेवलपर",
  selectDeveloper: "डेवलपर का चयन करें",
  sortBy: "तरह :",
  all: "सब",
  projectDescription: "परियोजना विवरण",
  projectStatus: "परियोजना की स्थिति",
  addProject: "प्रोजेक्ट जोड़ें",
};
